# shared bundle config
aliases:
  $design: source/client/design
  $ryota: source/client/ryota

# environments
development:
  mode: development
  url: http://ryota.nore

production:
  mode: production
  url: https://ryota.ro
  remote:
    ip: 199.247.17.83
    user: root
    path: /apps/ryota.ro