bundles:
- handle: server
  target: node

- handle: client
  target: web

general:
  aliases:
    $public: public
    $server: source/server
    $client: source/client
    $design: source/client/design
    $ryota: source/client/ryota

local:
  mode: development
  url: http://ryota.nore

server:
  mode: production
  url: https://ryota.ro
  remote:
    ip: 199.247.17.83
    user: root
    path: /apps/ryota.ro